language: cpp
compiler:
  - gcc
before_install:
  - sudo add-apt-repository ppa:kubuntu-ppa/backports -y
  - sudo add-apt-repository ppa:beineri/opt-qt551 -y
  - sudo add-apt-repository ppa:george-edison55/precise-backports -y
  - sudo apt-get update -qq
  - sudo apt-get install cmake qt-latest libquazip0-dev python-dev
before_script:
  - cd screencloud
  - mkdir build
  - cd build
  - cmake ..
script:
  - make
os:
  - linux