language: cpp
compiler:
  - gcc
before_install:
  - sudo add-apt-repository ppa:kubuntu-ppa/backports -y
  - sudo apt-get update -qq
  - sudo apt-get install libqxt-dev libquazip0-dev qtmobility-dev python2.7-dev
before_script:
  - cd screencloud
  - mkdir build
  - cd build
  - cmake ..
script:
  - make
os:
  - linux