#
# appimage.yaml to build ScreenCloud in Open Build Service (OBS)
#

app: screencloud

# resources required at build time
build:
  packages:
    - linuxdeployqt
    - cmake
    - sed
    - libQt5Core-devel
    - libQt5Core-private-headers-devel
    - libQt5Concurrent-devel
    - libQt5DBus-devel
    - libQt5Gui-devel
    - libQt5Gui-private-headers-devel
    - libQt5Multimedia-devel
    - libQt5Network-devel
    - libQt5OpenGL-devel
    - libQt5PrintSupport-devel
    - libQt5Quick-devel
    - libQt5Svg-devel
    - libQt5Sql-devel
    - libQt5Test-devel
    - libQt5Widgets-devel
    - libQt5Xml-devel
    - libQt5XmlPatterns-devel
    - libQt5X11Extras-devel
    - libqt5-qttools-devel
    - libquazip-qt5-devel
    - libpulse0
    - python-devel
    - zlib-devel
  git:
    - https://github.com/olav-st/screencloud.git
  svn:
    - http://svn.code.sf.net/p/pythonqt/code/trunk

script:
  - mv $BUILD_SOURCE_DIR/trunk $BUILD_SOURCE_DIR/pythonqt
  - cd $BUILD_SOURCE_DIR/pythonqt
#Hotfix https://sourceforge.net/p/pythonqt/discussion/631393/thread/a9358753/
  - sed -i -e 's/PythonQt_init_QtQml(0);/\/\/PythonQt_init_QtQml(0);/g' extensions/PythonQt_QtAll/PythonQt_QtAll.cpp
  - sed -i -e 's/PythonQt_init_QtQuick(0);/\/\/PythonQt_init_QtQuick(0);/g' extensions/PythonQt_QtAll/PythonQt_QtAll.cpp
#end
  - qmake-qt5
  - make -j4
#Hacky way to install PythonQt. From: https://aur.archlinux.org/packages/pythonqt/
  - mkdir -p /usr/include/PythonQt/{gui,extensions/PythonQt_QtAll}
  - cp src/*.h /usr/include/PythonQt/
  - cp src/gui/*.h /usr/include/PythonQt/gui/
  - cp extensions/PythonQt_QtAll/*.h /usr/include/PythonQt/extensions/PythonQt_QtAll/
  - mkdir -p /usr/lib
  - cp -a lib/*.so* /usr/lib64/ || cp -a lib/*.so* /usr/lib/
#end
  - cd $BUILD_SOURCE_DIR/screencloud*
  - mkdir build
  - cd build
  - cmake -DPYTHON_USE_PYTHON3=OFF -DPYTHONQT_INSTALL_DIR=$BUILD_SOURCE_DIR/pythonqt -DPYTHONQT_QTALL_INSTALL_DIR=$BUILD_SOURCE_DIR/pythonqt ..
  - make -j4
  - make install DESTDIR=$(readlink -f $BUILD_APPDIR) ; find $BUILD_APPDIR/
  - unset QTDIR; unset QT_PLUGIN_PATH ; unset LD_LIBRARY_PATH
#Fix for https://github.com/probonopd/linuxdeployqt/issues/52
  - cp /usr/lib*/pulseaudio/* /usr/lib64/ || cp /usr/lib*/pulseaudio/* /usr/lib/
#end
  - linuxdeployqt $BUILD_APPDIR/usr/local/share/applications/screencloud.desktop -bundle-non-qt-libs
  - linuxdeployqt $BUILD_APPDIR/usr/local/share/applications/screencloud.desktop -bundle-non-qt-libs
  - cp $BUILD_APPDIR/usr/local/share/applications/screencloud.desktop $BUILD_APPDIR
  - cp $BUILD_SOURCE_DIR/screencloud*/res/icons/screencloud.svg $BUILD_APPDIR
