name: screencloud
version: "1.3.0"
summary: Easy to use screenshot sharing application
description: Take a screenshot using one of the 3 hotkeys or simply click the ScreenCloud tray icon. You can choose where you want to save your screenshot.
confinement: devmode

apps:
  screencloud:
    command: desktop-launch screencloud.sh
    plugs: 
      - x11
      - network
      - home
      - unity7
      - opengl
      - pulseaudio
      - gsettings
      - network-bind #A local port is used to check if another screencloud process is running 

parts:
  screencloud:
    source: https://github.com/olav-st/screencloud.git
    source-tag: master
    plugin: cmake
    configflags: [-DPYTHON_USE_PYTHON3=OFF] #To avoid having to patch pythonqt
    build-packages:
      - g++
      - qtbase5-private-dev
      - libqt5svg5-dev
      - libqt5x11extras5-dev
      - qtmultimedia5-dev
      - libquazip5-dev
      - python2.7-dev
    stage-packages:
      - openssl
      - python2.7-minimal
      - libpython2.7-stdlib
      - libqt5x11extras5
      - libqt5multimedia5
      - libqt5multimedia5-plugins
      - dconf-gsettings-backend
    after: [pythonqt, pythonqt-install, desktop/qt5]

  pythonqt:
    source: https://sourceforge.net/code-snapshots/svn/p/py/pythonqt/code/pythonqt-code-428-trunk.zip
    source-subdir: pythonqt-code-428-trunk
    plugin: qmake
    qt-version: qt5
    options: 
      - LIBPATH += lib
      - LIBPATH += ../lib
      - LIBPATH += ../../lib
      - LIBPATH += ../../../lib
      - LIBPATH += ../../../../lib
    build-packages:
      - g++
      - qtbase5-dev
      - qttools5-dev
      - qtdeclarative5-dev
      - libqt5webkit5-dev
      - libqt5xmlpatterns5-dev
      - python2.7-dev

  pythonqt-install:
    plugin: copy
    source: parts/pythonqt
    files:
      src/pythonqt-code-428-trunk/src/*.h: usr/include/PythonQt/
      src/pythonqt-code-428-trunk/src/gui/*.h: usr/
      src/pythonqt-code-428-trunk/extensions/PythonQt_QtAll/*.h: usr/include/PythonQt/extensions/PythonQt_QtAll/
      build/pythonqt-code-428-trunk/lib/*: usr/lib/
    after: [pythonqt]